// Code generated by "stringer -type=Protocol"; DO NOT EDIT.

package registry

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FTP-0]
	_ = x[HTTP-1]
	_ = x[LOCAL-2]
}

const _Protocol_name = "FTPHTTPLOCAL"

var _Protocol_index = [...]uint8{0, 3, 7, 12}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
