---
repos:
  # Meta
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  # Generic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat-toc
          - mdformat-config
          - mdformat-gofmt
        args: ["--number", "--wrap", "80"]
  # YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
