name: build

on:
  push:
    branches:
      - master
  pull_request:
   git stat branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [ 1.17 ]
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}

      - name: Install dependencies
        run: |
            go version
            go get -u golang.org/x/lint/golint

      - name: Run tests
        run: go test ./...

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .
          golint .